In [1]:
# It is convention to import numpy as `np`
import numpy as np

# Arrays

You can make an array from a regular python list of numbers.

In [40]:
np.array([1, 7, 4, 2])

array([1, 7, 4, 2])

There are also functions for making specific arrays, such as a range of numbers. For example, make an array from 0 to 9:

In [42]:
a = np.arange(10)

a # Display a value in a jupyter notebook by just putting it on a line by itself.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Get the length of the array:


In [43]:
a.size

10

Get the number of dimensions:

In [44]:
a.ndim

1

The `shape` of the array is the length of each dimension. In this case, it's just 1 dimension of length 10.

In [45]:
a.shape

(10,)

Basic indexing of one-dimensional numpy arrays is similar to a regular python list.

Get the zeroth element:

In [46]:
a[0]

0

Get the last element:

In [47]:
a[-1]

9

Get the elements from [2,5):

In [48]:
a[2:5]

array([2, 3, 4])

Get every other element:

In [49]:
a[::2]

array([0, 2, 4, 6, 8])

# Matrices

A numpy matrix is just an array with more than one dimension.

Create a two dimensional array:

In [50]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Get the total number of elements in the array:

In [51]:
a.size

9

Get the number of dimensions:

In [53]:
a.ndim

2

Get the length of each of the dimensions:

In [55]:
a.shape

(3, 3)

Indexing two-dimensional arrays can be trickier.  Getting a single row is the same as a multidimensional python list:

In [56]:
a[0]

array([1, 2, 3])

As is getting a single element:

In [57]:
a[0][0]

1

Numpy also allows you to get a single column, something more difficult with python lists.
To do this, numpy uses commas to separate the indicies for each dimension.
So, for instance, to get the zeroth column you would do:

In [59]:
a[:,0]

array([1, 4, 7])

Let's break that down.  The first colon just says to select all the values, 
the same as if you used the selector on a list:

In [60]:
[1,2,3][:]

[1, 2, 3]

Then the comma is to separate the first dimension from the second.
If we just had `:,:` we would get the whole matrix:

In [61]:
a[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

But instead, after the comma we put just a 0, meaning that
we want just the zeroth column.  We could have put a 1 to get the first column:

In [62]:
a[:,1]

array([2, 5, 8])

Or get just the first and second columns:

In [63]:
a[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

We can use the same notation for rows as well.  For instance, to get the first two rows:

In [65]:
a[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

And then combining both we can get just the top left corner:

In [66]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

# Array Creation Functions

We've already seen how to create an array from a python list, or from a range of numbers.  But numpy also has built-in functions to create specific arrays.  For instance, to create an array of all zeros:

In [67]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

You can specify the shape when creating the array.  For instance, to create a 3x3 matrix of ones:

In [68]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

Besides `np.arange`, numpy can also create other number series.

Create an array of 10 elements evenly spaced between 10 and 100:

In [73]:
start = 10
stop = 100
n = 10

np.linspace(start,stop,n)

array([  10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,   90.,  100.])

Or create a series of 10 elements logarithmically spaced between 10 and 100.  This is useful if you want more numbers at the lower end of the range than at the higher.  Here the start and stop are given as exponents.

In [74]:
start = 1 # 10^1 = 10
stop = 2 # 10^2 = 100
n = 10

np.logspace(start,stop,n)

array([  10.        ,   12.91549665,   16.68100537,   21.5443469 ,
         27.82559402,   35.93813664,   46.41588834,   59.94842503,
         77.42636827,  100.        ])

# Generating Random Arrays